name: 'Install Yarn Dependencies and Cache'
description: 'Installs yarn dependencies (Yarn) with Node.js and caches them for faster workflows'

runs:
  using: 'composite'
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'yarn'

    - name: Enable Corepack
      shell: bash
      run: corepack enable

    - name: Check Corepack version
      shell: bash
      run: corepack --version

    - name: Get Yarn version from package.json
      id: get-yarn-version
      shell: bash
      run: |
        YARN_VERSION=$(jq -r '.packageManager | sub("yarn@"; "")' package.json)
        echo "YARN_VERSION=$YARN_VERSION" >> $GITHUB_OUTPUT

    - name: Use Yarn version from packageManager (Dynamically from package.json)
      shell: bash
      run: corepack prepare "yarn@${{ steps.get-yarn-version.outputs.YARN_VERSION }}" --activate

    - name: Check Yarn version (after Corepack prepare)
      shell: bash
      run: yarn --version

    - name: Install dependencies
      shell: bash
      run: yarn install --immutable