name: 'Install Dependencies'
description: 'Install Yarn Dependencies and Cache'
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Get yarn version
      id: yarn-version
      shell: bash
      run: echo "version=$(yarn --version)" >> $GITHUB_OUTPUT

    - name: Get yarn cache directory path for Yarn 1
      if: startsWith(steps.yarn-version.outputs.version, '1.')
      id: yarn-cache-dir-path
      shell: bash
      run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

    - name: Get yarn cache directory path for Yarn 2+
      if: ${{ !startsWith(steps.yarn-version.outputs.version, '1.') }}
      id: yarn-modern-cache-dir-path
      shell: bash
      run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

    - name: Determine cache path
      id: cache-path
      shell: bash
      run: |
        if [ -n "${{ steps.yarn-cache-dir-path.outputs.dir }}" ]; then
          echo "path=${{ steps.yarn-cache-dir-path.outputs.dir }}" >> $GITHUB_OUTPUT
        else
          echo "path=${{ steps.yarn-modern-cache-dir-path.outputs.dir }}" >> $GITHUB_OUTPUT
        fi

    - uses: actions/cache@v4
      id: yarn-cache
      with:
        path: ${{ steps.cache-path.outputs.path }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      shell: bash
      run: yarn install --immutable