name: CI/CD Pipeline for app m-cqrs

on:
  push:
    branches:
      - "main"
    paths:
      - 'typescript/apps/m-cqrs/**'

jobs:
  deploy-app:
    uses: ./.github/workflows/workflow-call-deploy-app.yml
    with:
      app_name: m-cqrs
      docker_repository: m-cqrs # Make sure this matches your ECR repo name
      eb_application_name: CQRS-test # Your EB application name
      eb_environment_name: m-sqrs # Your EB environment name
      eb_version_label_suffix: m-sqrs
      container_port: 8000
      host_port: 80  
    secrets: inherit