name: Tests

run-name: Tests ${{ github.head_ref || github.ref }}

on:
  push:
    branches: [ci-tests]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
  
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Use Setup Yarn action
        uses: ./.github/actions/setup-yarn

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
  
      - name: build
        run: |
          yarn
          yarn build
          yarn test
        working-directory: ./
          